import { lazy } from 'react'

export const Home = lazy(() => import('@/pages/Home'))
export const TalleresMoviles = lazy(() => import('@/pages/TalleresMoviles'))
export const VentanasLunetas = lazy(() => import('@/pages/VentanasLunetas'))
export const EquipamientoEscolar = lazy(() => import('@/pages/EquipamientoEscolar'))
export const Banquetas = lazy(() => import('@/pages/Banquetas'))
export const Butacas = lazy(() => import('@/pages/Butacas'))
export const Accesorios = lazy(() => import('@/pages/Accesorios'))
export const ProteccionCabina = lazy(() => import('@/pages/ProteccionCabina'))
export const CambioPisos = lazy(() => import('@/pages/CambioPisos'))
export const Reclinaciones = lazy(() => import('@/pages/Reclinaciones'))
export const Fundas = lazy(() => import('@/pages/Fundas'))
export const Literas = lazy(() => import('@/pages/Literas'))
export const Tapiceria = lazy(() => import('@/pages/Tapiceria'))
export const Trabajos = lazy(() => import('@/pages/Trabajos'))
export const Contacto = lazy(() => import('@/pages/Contacto'))
export const SobreNosotros = lazy(() => import('@/pages/SobreNosotros'))
export const NotFound = lazy(() => import('@/pages/NotFound'))
