/**
 * Catálogo canónico runtime — espejo de TRABAJOS_PORTFOLIO en src/content/work.js.
 * Fuente para paridad CMS Proyectos ↔ Trabajos / Servicios.
 */
export const RUNTIME_WORK_PROJECT_CATALOG = [
  {
    id: 'TM-001',
    title: 'Taller móvil equipado en terreno',
    serviceCategory: 'talleres-moviles',
    description:
      'Conversión de utilitario con mobiliario técnico, revestimiento interior y organización modular.',
    imageFile: 'src/assets/images/talleres/tr143.jpg',
  },
  {
    id: 'TM-002',
    title: 'Interior de unidad móvil técnica',
    serviceCategory: 'talleres-moviles',
    description: 'Habitáculo adaptado para operación y almacenamiento de herramientas.',
    imageFile: 'src/assets/images/talleres/tr247.jpg',
  },
  {
    id: 'TM-003',
    title: 'Taller móvil Toyota Hiace',
    serviceCategory: 'talleres-moviles',
    description:
      'Equipamiento interior con electricidad y terminaciones para servicio en ruta.',
    imageFile: 'src/assets/images/trabajos/taller-hiace.jpg',
  },
  {
    id: 'TM-004',
    title: 'Furgón adaptado a taller móvil',
    serviceCategory: 'talleres-moviles',
    description: 'Distribución interior y revestimientos para trabajo técnico.',
    imageFile: 'src/assets/images/talleres/tr11.jpg',
  },
  {
    id: 'TM-005',
    title: 'Compartimientos interiores modulares',
    serviceCategory: 'talleres-moviles',
    description: 'Optimización de espacios para operación en terreno.',
    imageFile: 'src/assets/images/talleres/tr12.jpg',
  },
  {
    id: 'TM-006',
    title: 'Revestimiento interior utilitario',
    serviceCategory: 'talleres-moviles',
    description: 'Terminaciones resistentes para uso intensivo.',
    imageFile: 'src/assets/images/talleres/tr9.jpg',
  },
  {
    id: 'VL-001',
    title: 'Kit ventanas Renault Master',
    serviceCategory: 'ventanas-lunetas',
    description: 'Ventiletes y luneta con terminación sellada profesional.',
    imageFile: 'src/assets/images/trabajos/ventanas-master.jpg',
  },
  {
    id: 'VL-002',
    title: 'Ventanas laterales en utilitario',
    serviceCategory: 'ventanas-lunetas',
    description: 'Instalación con marco de aluminio electropintado.',
    imageFile: 'src/assets/images/ventanas/vent1.jpg',
  },
  {
    id: 'VL-003',
    title: 'Ventanas corredizas de aluminio',
    serviceCategory: 'ventanas-lunetas',
    description: 'Vidrios templados y terminación industrial.',
    imageFile: 'src/assets/images/ventanas/vent2.jpg',
  },
  {
    id: 'VL-004',
    title: 'Luneta y ventiletes traseros',
    serviceCategory: 'ventanas-lunetas',
    description: 'Cierre perimetral y acabado en taller Utilcar.',
    imageFile: 'src/assets/images/ventanas/vent3.jpg',
  },
  {
    id: 'VL-005',
    title: 'Equipamiento ventanas Toyota',
    serviceCategory: 'ventanas-lunetas',
    description: 'Conversión según carrocería y modelo.',
    imageFile: 'src/assets/images/ventanas/marcas/toyota/toyota.jpg',
  },
  {
    id: 'VL-006',
    title: 'Ventanas Peugeot Boxer',
    serviceCategory: 'ventanas-lunetas',
    description: 'Ventiletes y luneta para chasis utilitario.',
    imageFile: 'src/assets/images/ventanas/marcas/peugeot/peugeot.jfif',
  },
  {
    id: 'VL-007',
    title: 'Kit ventanas Renault',
    serviceCategory: 'ventanas-lunetas',
    description: 'Instalación con sellado profesional.',
    imageFile: 'src/assets/images/ventanas/marcas/renault/renault.jpg',
  },
  {
    id: 'VL-008',
    title: 'Ventanas Fiat Ducato',
    serviceCategory: 'ventanas-lunetas',
    description: 'Compatibilidad con batalla y configuración del vehículo.',
    imageFile: 'src/assets/images/ventanas/marcas/fiat/fiat.jpg',
  },
  {
    id: 'VL-009',
    title: 'Ventanas Citroën Jumper',
    serviceCategory: 'ventanas-lunetas',
    description: 'Terminaciones en aluminio electropintado.',
    imageFile: 'src/assets/images/ventanas/marcas/citroen/citroen-1.jfif',
  },
  {
    id: 'VL-010',
    title: 'Equipamiento Chevrolet',
    serviceCategory: 'ventanas-lunetas',
    description: 'Ventanas y equipamiento integral en habitáculo.',
    imageFile: 'src/assets/images/ventanas/marcas/chevrolet/chev1.jpg',
  },
  {
    id: 'EE-001',
    title: 'Equipamiento escolar en bus',
    serviceCategory: 'equipamiento-escolar',
    description: 'Butacas homologadas y distribución para transporte escolar.',
    imageFile: 'src/assets/images/escolar/ee350.jpg',
  },
  {
    id: 'EE-002',
    title: 'Interior escolar terminado',
    serviceCategory: 'equipamiento-escolar',
    description: 'Señalética, asientos y terminaciones interiores.',
    imageFile: 'src/assets/images/escolar/ee351.jfif',
  },
  {
    id: 'EE-003',
    title: 'Conversión transporte escolar',
    serviceCategory: 'equipamiento-escolar',
    description: 'Instalación conforme a requerimientos de operación.',
    imageFile: 'src/assets/images/escolar/ee352.jpg',
  },
  {
    id: 'BQ-001',
    title: 'Banquetas traslado de personal',
    serviceCategory: 'banquetas',
    description: 'Fabricación en tubo reforzado con tapizado técnico.',
    imageFile: 'src/assets/images/banquetas/traslado/banq_tras_pers.jpg',
  },
  {
    id: 'BQ-002',
    title: 'Minibús con banquetas corporativas',
    serviceCategory: 'banquetas',
    description: 'Distribución interior y pasillo homologado.',
    imageFile: 'src/assets/images/banquetas/traslado/banq_tras_pers2.jpg',
  },
  {
    id: 'BQ-003',
    title: 'Peugeot Boxer con banquetas',
    serviceCategory: 'banquetas',
    description: 'Configuración 2+1 con terminaciones profesionales.',
    imageFile: 'src/assets/images/trabajos/minibus-boxer.jpg',
  },
  {
    id: 'BQ-004',
    title: 'Banquetas adultos',
    serviceCategory: 'banquetas',
    description: 'Estructura MIG y suspensión con resortes inox.',
    imageFile: 'src/assets/images/banquetas/adultos/IMG_0118.jfif',
  },
  {
    id: 'BQ-005',
    title: 'Banquetas línea escolar',
    serviceCategory: 'banquetas',
    description: 'Espuma alta densidad y cinturones de dos puntas.',
    imageFile: 'src/assets/images/banquetas/escolares/banq_esc.jpg',
  },
  {
    id: 'BQ-006',
    title: 'Equipamiento escolar en banqueta',
    serviceCategory: 'banquetas',
    description: 'Tapiz vinil técnico y patas electropintadas.',
    imageFile: 'src/assets/images/banquetas/escolares/banq_esc1.jpg',
  },
  {
    id: 'BT-001',
    title: 'Butacas a medida — tapizado',
    serviceCategory: 'butacas',
    description: 'Fabricación con matrices propias y terminación premium.',
    imageFile: 'src/assets/images/butacas/IMG_0148.jfif',
  },
  {
    id: 'BT-002',
    title: 'Detalle de costuras y acabado',
    serviceCategory: 'butacas',
    description: 'Tapizados técnicos y control de calidad en taller.',
    imageFile: 'src/assets/images/butacas/IMG_0149.jfif',
  },
  {
    id: 'BT-003',
    title: 'Butacas personalizadas',
    serviceCategory: 'butacas',
    description: 'Configuración según ergonomía y uso del vehículo.',
    imageFile: 'src/assets/images/butacas/IMG_0150.jfif',
  },
  {
    id: 'AC-001',
    title: 'Cabeceras de seguridad',
    serviceCategory: 'accesorios',
    description: 'Poliuretano inyectado y tapiz a elección.',
    imageFile: 'src/assets/images/accesorios/cabeceras/cabeceras.jpg',
  },
  {
    id: 'AC-002',
    title: 'Apoya brazos articulado',
    serviceCategory: 'accesorios',
    description: 'Confort en viajes prolongados con sistema abatible.',
    imageFile: 'src/assets/images/accesorios/apoya-brazos/apoya_brazos.jpg',
  },
  {
    id: 'AC-003',
    title: 'Baliza escolar 12 V',
    serviceCategory: 'accesorios',
    description: 'Señalización preventiva imantada color amarillo.',
    imageFile: 'src/assets/images/accesorios/balizas/baliza.jpg',
  },
  {
    id: 'AC-004',
    title: 'Distintivo escolar reglamentario',
    serviceCategory: 'accesorios',
    description: 'Letrero «Escolares» con fijación temporal normativa.',
    imageFile: 'src/assets/images/accesorios/distintivo-escolar/esc.jpg',
  },
]
